deps = Dir["*.tex"] + Dir["*.*bx"] + Dir['*.bib'] + [:graphs]

main = Dir['sig*.tex'].first
main_noext = main.sub '.tex', ''
main_pdf = main.sub '.tex', '.pdf'

file main_pdf => deps do |t|
  sh "xelatex #{main_noext}"
  sh "biber #{main_noext}"
  sh "xelatex #{main_noext}"
end

desc "sestavit dokument"
task :default => [main_pdf]

desc "smazat vedlejsi produkty sazby latexem"
task :clean do
  %w{aux bbl dvi bcf blg log out pdf run.xml *~}.each do |s|
    unless Dir['*.'+s].empty?
      sh "rm *."+s
    end
  end
end

desc "vygenerovat grafy"
task :graphs do
  sh 'Rscript graphs/graphs.R'
  sh 'Rscript graphs/analysis.R'
end
